version: "3.8"
services:
  pet-ecommerce-db-dev:
    image: postgres:14.1-alpine
    container_name: pet-ecommerce-db-dev
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
  pet-ecommerce-s3-dev:
    image: scireum/s3-ninja
    container_name: pet-ecommerce-s3-dev
    ports:
      - 9444:9000
