version: "3.8"
services:
  dev-database:
    image: postgres:14.1-alpine
    container_name: dev-database
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ecommerce
    ports:
      - "5433:5432"
  dev-s3:
    image: scireum/s3-ninja
    container_name: dev-s3
    ports:
      - 9444:9000
